/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SimpleComponent {
    }
    interface SimpleComponentDefaultSlot {
    }
    interface SimpleComponentNoShadow {
    }
}
declare global {
    interface HTMLSimpleComponentElement extends Components.SimpleComponent, HTMLStencilElement {
    }
    var HTMLSimpleComponentElement: {
        prototype: HTMLSimpleComponentElement;
        new (): HTMLSimpleComponentElement;
    };
    interface HTMLSimpleComponentDefaultSlotElement extends Components.SimpleComponentDefaultSlot, HTMLStencilElement {
    }
    var HTMLSimpleComponentDefaultSlotElement: {
        prototype: HTMLSimpleComponentDefaultSlotElement;
        new (): HTMLSimpleComponentDefaultSlotElement;
    };
    interface HTMLSimpleComponentNoShadowElement extends Components.SimpleComponentNoShadow, HTMLStencilElement {
    }
    var HTMLSimpleComponentNoShadowElement: {
        prototype: HTMLSimpleComponentNoShadowElement;
        new (): HTMLSimpleComponentNoShadowElement;
    };
    interface HTMLElementTagNameMap {
        "simple-component": HTMLSimpleComponentElement;
        "simple-component-default-slot": HTMLSimpleComponentDefaultSlotElement;
        "simple-component-no-shadow": HTMLSimpleComponentNoShadowElement;
    }
}
declare namespace LocalJSX {
    interface SimpleComponent {
    }
    interface SimpleComponentDefaultSlot {
    }
    interface SimpleComponentNoShadow {
    }
    interface IntrinsicElements {
        "simple-component": SimpleComponent;
        "simple-component-default-slot": SimpleComponentDefaultSlot;
        "simple-component-no-shadow": SimpleComponentNoShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "simple-component": LocalJSX.SimpleComponent & JSXBase.HTMLAttributes<HTMLSimpleComponentElement>;
            "simple-component-default-slot": LocalJSX.SimpleComponentDefaultSlot & JSXBase.HTMLAttributes<HTMLSimpleComponentDefaultSlotElement>;
            "simple-component-no-shadow": LocalJSX.SimpleComponentNoShadow & JSXBase.HTMLAttributes<HTMLSimpleComponentNoShadowElement>;
        }
    }
}
